export { CompanyInformationForm } from './CompanyInformationForm'
export { RegisteredOfficeAddressForm } from './RegisteredOfficeAddressForm'
export { PrimaryContactForm } from './PrimaryContactForm'
export { default as BeneficiaryForm } from './BeneficiaryForm'
export { default as DirectorForm } from './DirectorForm'
