export { CompanyInformationForm } from './CompanyInformationForm'
export { RegisteredOfficeAddressForm } from './RegisteredOfficeAddressForm'
export { PrimaryContactForm } from './PrimaryContactForm'
export { BeneficiaryForm } from './BeneficiaryForm'
export { DirectorForm } from './DirectorForm'
