export { default as Login } from './Login'
export { default as Reset } from './Reset'
export { default as Forgot } from './Forgot'
export { default as SignUp } from './SignUp'
export { default as KYC } from './KYC'
export { default as NotFound } from './NotFound'
